<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LAPTOP-QFKR4O5H" name="TestCases.IdentifyCoursesTest" tests="60" failures="21" timestamp="05 Oct 2020 08:04:07 GMT" time="1471.144" errors="0">
  <testcase name="searchTest" time="109.004" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="searchTest" time="72.945" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="searchTest" time="117.921" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="10.886" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="20.643" classname="TestCases.IdentifyCoursesTest">
    <failure type="java.lang.AssertionError" message="Error message NOT displayed, which is a failure!">
      <![CDATA[java.lang.AssertionError: Error message NOT displayed, which is a failure!
at org.testng.Assert.fail(Assert.java:96)
at BaseClasses.BaseTestClass.reportFail(BaseTestClass.java:174)
at PageClasses.CourseraForCampusPage.fillAndSubmitForm(CourseraForCampusPage.java:117)
at TestCases.IdentifyCoursesTest.formTest(IdentifyCoursesTest.java:66)
at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- formTest -->
  <testcase name="formTest" time="10.897" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="19.797" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="9.480" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="15.997" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="19.151" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="19.815" classname="TestCases.IdentifyCoursesTest">
    <failure type="java.lang.AssertionError" message="Error message NOT displayed, which is a failure!">
      <![CDATA[java.lang.AssertionError: Error message NOT displayed, which is a failure!
at org.testng.Assert.fail(Assert.java:96)
at BaseClasses.BaseTestClass.reportFail(BaseTestClass.java:174)
at PageClasses.CourseraForCampusPage.fillAndSubmitForm(CourseraForCampusPage.java:117)
at TestCases.IdentifyCoursesTest.formTest(IdentifyCoursesTest.java:66)
at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- formTest -->
  <testcase name="formTest" time="21.055" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="16.663" classname="TestCases.IdentifyCoursesTest">
    <failure type="java.lang.AssertionError" message="Error message NOT displayed, which is a failure!">
      <![CDATA[java.lang.AssertionError: Error message NOT displayed, which is a failure!
at org.testng.Assert.fail(Assert.java:96)
at BaseClasses.BaseTestClass.reportFail(BaseTestClass.java:174)
at PageClasses.CourseraForCampusPage.fillAndSubmitForm(CourseraForCampusPage.java:117)
at TestCases.IdentifyCoursesTest.formTest(IdentifyCoursesTest.java:66)
at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- formTest -->
  <testcase name="formTest" time="93.477" classname="TestCases.IdentifyCoursesTest">
    <failure type="java.lang.AssertionError" message="Error message NOT displayed, which is a failure!">
      <![CDATA[java.lang.AssertionError: Error message NOT displayed, which is a failure!
at org.testng.Assert.fail(Assert.java:96)
at BaseClasses.BaseTestClass.reportFail(BaseTestClass.java:174)
at PageClasses.CourseraForCampusPage.fillAndSubmitForm(CourseraForCampusPage.java:117)
at TestCases.IdentifyCoursesTest.formTest(IdentifyCoursesTest.java:66)
at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- formTest -->
  <testcase name="formTest" time="27.326" classname="TestCases.IdentifyCoursesTest">
    <failure type="java.lang.AssertionError" message="Error message NOT displayed, which is a failure!">
      <![CDATA[java.lang.AssertionError: Error message NOT displayed, which is a failure!
at org.testng.Assert.fail(Assert.java:96)
at BaseClasses.BaseTestClass.reportFail(BaseTestClass.java:174)
at PageClasses.CourseraForCampusPage.fillAndSubmitForm(CourseraForCampusPage.java:117)
at TestCases.IdentifyCoursesTest.formTest(IdentifyCoursesTest.java:66)
at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- formTest -->
  <testcase name="formTest" time="16.798" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="19.489" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="19.489" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="17.651" classname="TestCases.IdentifyCoursesTest">
    <failure type="java.lang.AssertionError" message="Error message NOT displayed, which is a failure!">
      <![CDATA[java.lang.AssertionError: Error message NOT displayed, which is a failure!
at org.testng.Assert.fail(Assert.java:96)
at BaseClasses.BaseTestClass.reportFail(BaseTestClass.java:174)
at PageClasses.CourseraForCampusPage.fillAndSubmitForm(CourseraForCampusPage.java:117)
at TestCases.IdentifyCoursesTest.formTest(IdentifyCoursesTest.java:66)
at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- formTest -->
  <testcase name="formTest" time="28.055" classname="TestCases.IdentifyCoursesTest">
    <failure type="java.lang.AssertionError" message="Error message NOT displayed, which is a failure!">
      <![CDATA[java.lang.AssertionError: Error message NOT displayed, which is a failure!
at org.testng.Assert.fail(Assert.java:96)
at BaseClasses.BaseTestClass.reportFail(BaseTestClass.java:174)
at PageClasses.CourseraForCampusPage.fillAndSubmitForm(CourseraForCampusPage.java:117)
at TestCases.IdentifyCoursesTest.formTest(IdentifyCoursesTest.java:66)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- formTest -->
  <testcase name="formTest" time="13.513" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="12.409" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="25.587" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="20.750" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="21.905" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="24.828" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="13.050" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="25.617" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="9.377" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="11.689" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="12.563" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="14.676" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="19.793" classname="TestCases.IdentifyCoursesTest">
    <failure type="java.lang.AssertionError" message="Error message NOT displayed, which is a failure!">
      <![CDATA[java.lang.AssertionError: Error message NOT displayed, which is a failure!
at org.testng.Assert.fail(Assert.java:96)
at BaseClasses.BaseTestClass.reportFail(BaseTestClass.java:174)
at PageClasses.CourseraForCampusPage.fillAndSubmitForm(CourseraForCampusPage.java:117)
at TestCases.IdentifyCoursesTest.formTest(IdentifyCoursesTest.java:66)
at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- formTest -->
  <testcase name="formTest" time="16.568" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="10.013" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="9.368" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="25.262" classname="TestCases.IdentifyCoursesTest">
    <failure type="java.lang.AssertionError" message="Error message NOT displayed, which is a failure!">
      <![CDATA[java.lang.AssertionError: Error message NOT displayed, which is a failure!
at org.testng.Assert.fail(Assert.java:96)
at BaseClasses.BaseTestClass.reportFail(BaseTestClass.java:174)
at PageClasses.CourseraForCampusPage.fillAndSubmitForm(CourseraForCampusPage.java:117)
at TestCases.IdentifyCoursesTest.formTest(IdentifyCoursesTest.java:66)
at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- formTest -->
  <testcase name="formTest" time="19.202" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="74.717" classname="TestCases.IdentifyCoursesTest">
    <failure type="java.lang.AssertionError" message="Error message NOT displayed, which is a failure!">
      <![CDATA[java.lang.AssertionError: Error message NOT displayed, which is a failure!
at org.testng.Assert.fail(Assert.java:96)
at BaseClasses.BaseTestClass.reportFail(BaseTestClass.java:174)
at PageClasses.CourseraForCampusPage.fillAndSubmitForm(CourseraForCampusPage.java:117)
at TestCases.IdentifyCoursesTest.formTest(IdentifyCoursesTest.java:66)
at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- formTest -->
  <testcase name="formTest" time="31.331" classname="TestCases.IdentifyCoursesTest">
    <failure type="java.lang.AssertionError" message="Error message NOT displayed, which is a failure!">
      <![CDATA[java.lang.AssertionError: Error message NOT displayed, which is a failure!
at org.testng.Assert.fail(Assert.java:96)
at BaseClasses.BaseTestClass.reportFail(BaseTestClass.java:174)
at PageClasses.CourseraForCampusPage.fillAndSubmitForm(CourseraForCampusPage.java:117)
at TestCases.IdentifyCoursesTest.formTest(IdentifyCoursesTest.java:66)
at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- formTest -->
  <testcase name="formTest" time="16.655" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="15.074" classname="TestCases.IdentifyCoursesTest">
    <failure type="java.lang.AssertionError" message="Error message NOT displayed, which is a failure!">
      <![CDATA[java.lang.AssertionError: Error message NOT displayed, which is a failure!
at org.testng.Assert.fail(Assert.java:96)
at BaseClasses.BaseTestClass.reportFail(BaseTestClass.java:174)
at PageClasses.CourseraForCampusPage.fillAndSubmitForm(CourseraForCampusPage.java:117)
at TestCases.IdentifyCoursesTest.formTest(IdentifyCoursesTest.java:66)
at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- formTest -->
  <testcase name="formTest" time="16.557" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="16.399" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="20.639" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="21.489" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="10.630" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="15.102" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="18.605" classname="TestCases.IdentifyCoursesTest">
    <failure type="java.lang.AssertionError" message="Error message NOT displayed, which is a failure!">
      <![CDATA[java.lang.AssertionError: Error message NOT displayed, which is a failure!
at org.testng.Assert.fail(Assert.java:96)
at BaseClasses.BaseTestClass.reportFail(BaseTestClass.java:174)
at PageClasses.CourseraForCampusPage.fillAndSubmitForm(CourseraForCampusPage.java:117)
at TestCases.IdentifyCoursesTest.formTest(IdentifyCoursesTest.java:66)
at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- formTest -->
  <testcase name="formTest" time="9.918" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="20.144" classname="TestCases.IdentifyCoursesTest">
    <failure type="java.lang.AssertionError" message="Error message NOT displayed, which is a failure!">
      <![CDATA[java.lang.AssertionError: Error message NOT displayed, which is a failure!
at org.testng.Assert.fail(Assert.java:96)
at BaseClasses.BaseTestClass.reportFail(BaseTestClass.java:174)
at PageClasses.CourseraForCampusPage.fillAndSubmitForm(CourseraForCampusPage.java:117)
at TestCases.IdentifyCoursesTest.formTest(IdentifyCoursesTest.java:66)
at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- formTest -->
  <testcase name="formTest" time="17.453" classname="TestCases.IdentifyCoursesTest">
    <failure type="java.lang.AssertionError" message="Error message NOT displayed, which is a failure!">
      <![CDATA[java.lang.AssertionError: Error message NOT displayed, which is a failure!
at org.testng.Assert.fail(Assert.java:96)
at BaseClasses.BaseTestClass.reportFail(BaseTestClass.java:174)
at PageClasses.CourseraForCampusPage.fillAndSubmitForm(CourseraForCampusPage.java:117)
at TestCases.IdentifyCoursesTest.formTest(IdentifyCoursesTest.java:66)
at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- formTest -->
  <testcase name="formTest" time="21.751" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="17.958" classname="TestCases.IdentifyCoursesTest">
    <failure type="java.lang.AssertionError" message="Error message NOT displayed, which is a failure!">
      <![CDATA[java.lang.AssertionError: Error message NOT displayed, which is a failure!
at org.testng.Assert.fail(Assert.java:96)
at BaseClasses.BaseTestClass.reportFail(BaseTestClass.java:174)
at PageClasses.CourseraForCampusPage.fillAndSubmitForm(CourseraForCampusPage.java:117)
at TestCases.IdentifyCoursesTest.formTest(IdentifyCoursesTest.java:66)
at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- formTest -->
  <testcase name="formTest" time="33.995" classname="TestCases.IdentifyCoursesTest">
    <failure type="java.lang.AssertionError" message="Error message NOT displayed, which is a failure!">
      <![CDATA[java.lang.AssertionError: Error message NOT displayed, which is a failure!
at org.testng.Assert.fail(Assert.java:96)
at BaseClasses.BaseTestClass.reportFail(BaseTestClass.java:174)
at PageClasses.CourseraForCampusPage.fillAndSubmitForm(CourseraForCampusPage.java:117)
at TestCases.IdentifyCoursesTest.formTest(IdentifyCoursesTest.java:66)
at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- formTest -->
  <testcase name="formTest" time="17.156" classname="TestCases.IdentifyCoursesTest">
    <failure type="java.lang.AssertionError" message="Error message NOT displayed, which is a failure!">
      <![CDATA[java.lang.AssertionError: Error message NOT displayed, which is a failure!
at org.testng.Assert.fail(Assert.java:96)
at BaseClasses.BaseTestClass.reportFail(BaseTestClass.java:174)
at PageClasses.CourseraForCampusPage.fillAndSubmitForm(CourseraForCampusPage.java:117)
at TestCases.IdentifyCoursesTest.formTest(IdentifyCoursesTest.java:66)
at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- formTest -->
  <testcase name="formTest" time="29.122" classname="TestCases.IdentifyCoursesTest">
    <failure type="java.lang.AssertionError" message="Error message NOT displayed, which is a failure!">
      <![CDATA[java.lang.AssertionError: Error message NOT displayed, which is a failure!
at org.testng.Assert.fail(Assert.java:96)
at BaseClasses.BaseTestClass.reportFail(BaseTestClass.java:174)
at PageClasses.CourseraForCampusPage.fillAndSubmitForm(CourseraForCampusPage.java:117)
at TestCases.IdentifyCoursesTest.formTest(IdentifyCoursesTest.java:66)
at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- formTest -->
  <testcase name="formTest" time="19.194" classname="TestCases.IdentifyCoursesTest">
    <failure type="java.lang.AssertionError" message="Error message NOT displayed, which is a failure!">
      <![CDATA[java.lang.AssertionError: Error message NOT displayed, which is a failure!
at org.testng.Assert.fail(Assert.java:96)
at BaseClasses.BaseTestClass.reportFail(BaseTestClass.java:174)
at PageClasses.CourseraForCampusPage.fillAndSubmitForm(CourseraForCampusPage.java:117)
at TestCases.IdentifyCoursesTest.formTest(IdentifyCoursesTest.java:66)
at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- formTest -->
  <testcase name="formTest" time="19.072" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="15.474" classname="TestCases.IdentifyCoursesTest">
    <failure type="java.lang.AssertionError" message="Error message NOT displayed, which is a failure!">
      <![CDATA[java.lang.AssertionError: Error message NOT displayed, which is a failure!
at org.testng.Assert.fail(Assert.java:96)
at BaseClasses.BaseTestClass.reportFail(BaseTestClass.java:174)
at PageClasses.CourseraForCampusPage.fillAndSubmitForm(CourseraForCampusPage.java:117)
at TestCases.IdentifyCoursesTest.formTest(IdentifyCoursesTest.java:66)
at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- formTest -->
</testsuite> <!-- TestCases.IdentifyCoursesTest -->
