<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LAPTOP-QFKR4O5H" name="TestCases.IdentifyCoursesTest" tests="20" failures="7" timestamp="10 Oct 2020 14:26:43 GMT" time="290.407" errors="0">
  <testcase name="searchTest" time="87.578" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="7.701" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="13.174" classname="TestCases.IdentifyCoursesTest">
    <failure type="java.lang.AssertionError" message="Error message NOT displayed, which is a failure!">
      <![CDATA[java.lang.AssertionError: Error message NOT displayed, which is a failure!
at org.testng.Assert.fail(Assert.java:96)
at BaseClasses.BaseTestClass.reportFail(BaseTestClass.java:178)
at PageClasses.CourseraForCampusPage.fillAndSubmitForm(CourseraForCampusPage.java:131)
at TestCases.IdentifyCoursesTest.formTest(IdentifyCoursesTest.java:73)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- formTest -->
  <testcase name="formTest" time="7.740" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="7.951" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="7.781" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="13.971" classname="TestCases.IdentifyCoursesTest">
    <failure type="java.lang.AssertionError" message="Error message NOT displayed, which is a failure!">
      <![CDATA[java.lang.AssertionError: Error message NOT displayed, which is a failure!
at org.testng.Assert.fail(Assert.java:96)
at BaseClasses.BaseTestClass.reportFail(BaseTestClass.java:178)
at PageClasses.CourseraForCampusPage.fillAndSubmitForm(CourseraForCampusPage.java:131)
at TestCases.IdentifyCoursesTest.formTest(IdentifyCoursesTest.java:73)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- formTest -->
  <testcase name="formTest" time="8.190" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="13.196" classname="TestCases.IdentifyCoursesTest">
    <failure type="java.lang.AssertionError" message="Error message NOT displayed, which is a failure!">
      <![CDATA[java.lang.AssertionError: Error message NOT displayed, which is a failure!
at org.testng.Assert.fail(Assert.java:96)
at BaseClasses.BaseTestClass.reportFail(BaseTestClass.java:178)
at PageClasses.CourseraForCampusPage.fillAndSubmitForm(CourseraForCampusPage.java:131)
at TestCases.IdentifyCoursesTest.formTest(IdentifyCoursesTest.java:73)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- formTest -->
  <testcase name="formTest" time="8.291" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="13.358" classname="TestCases.IdentifyCoursesTest">
    <failure type="java.lang.AssertionError" message="Error message NOT displayed, which is a failure!">
      <![CDATA[java.lang.AssertionError: Error message NOT displayed, which is a failure!
at org.testng.Assert.fail(Assert.java:96)
at BaseClasses.BaseTestClass.reportFail(BaseTestClass.java:178)
at PageClasses.CourseraForCampusPage.fillAndSubmitForm(CourseraForCampusPage.java:131)
at TestCases.IdentifyCoursesTest.formTest(IdentifyCoursesTest.java:73)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- formTest -->
  <testcase name="formTest" time="7.753" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="7.584" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="13.015" classname="TestCases.IdentifyCoursesTest">
    <failure type="java.lang.AssertionError" message="Error message NOT displayed, which is a failure!">
      <![CDATA[java.lang.AssertionError: Error message NOT displayed, which is a failure!
at org.testng.Assert.fail(Assert.java:96)
at BaseClasses.BaseTestClass.reportFail(BaseTestClass.java:178)
at PageClasses.CourseraForCampusPage.fillAndSubmitForm(CourseraForCampusPage.java:131)
at TestCases.IdentifyCoursesTest.formTest(IdentifyCoursesTest.java:73)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- formTest -->
  <testcase name="formTest" time="7.683" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="7.627" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="14.019" classname="TestCases.IdentifyCoursesTest">
    <failure type="java.lang.AssertionError" message="Error message NOT displayed, which is a failure!">
      <![CDATA[java.lang.AssertionError: Error message NOT displayed, which is a failure!
at org.testng.Assert.fail(Assert.java:96)
at BaseClasses.BaseTestClass.reportFail(BaseTestClass.java:178)
at PageClasses.CourseraForCampusPage.fillAndSubmitForm(CourseraForCampusPage.java:131)
at TestCases.IdentifyCoursesTest.formTest(IdentifyCoursesTest.java:73)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- formTest -->
  <testcase name="formTest" time="9.287" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="14.468" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="20.040" classname="TestCases.IdentifyCoursesTest">
    <failure type="java.lang.AssertionError" message="Error message NOT displayed, which is a failure!">
      <![CDATA[java.lang.AssertionError: Error message NOT displayed, which is a failure!
at org.testng.Assert.fail(Assert.java:96)
at BaseClasses.BaseTestClass.reportFail(BaseTestClass.java:178)
at PageClasses.CourseraForCampusPage.fillAndSubmitForm(CourseraForCampusPage.java:131)
at TestCases.IdentifyCoursesTest.formTest(IdentifyCoursesTest.java:73)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- formTest -->
</testsuite> <!-- TestCases.IdentifyCoursesTest -->
